package appservice

import (
	"fmt"
	"path/filepath"
	"strings"

	"github.com/kardianos/service"

	"github.com/erayselim/offveil/offveil-core/internal/appdir"
)

// LaunchDaemonPlist is the system-domain plist kardianos/service writes.
const LaunchDaemonPlist = "/Library/LaunchDaemons/" + Name + ".plist"

// SudoersPath grants %admin passwordless start/stop (Windows SERVICE_START analogue).
const SudoersPath = "/etc/sudoers.d/offveil"

// NeedsInstallPrefix matches the UI bootstrap error so Phase 6 can reuse it.
const NeedsInstallPrefix = "needs_install:"

// CanonicalBinary is the LaunchDaemon Program after setup.
func CanonicalBinary() string {
	return filepath.Join(appdir.Root(), "offveil-core")
}

// DarwinLaunchdOptions is the demand-start set. File is not *_darwin.go so
// Windows tests can lock KeepAlive=false (must not become the default true).
func DarwinLaunchdOptions() service.KeyValue {
	return service.KeyValue{
		"KeepAlive":     false,
		"RunAtLoad":     false,
		"UserService":   false,
		"SessionCreate": false,
		"LogDirectory":  filepath.Join(appdir.Root(), "logs"),
	}
}

// SudoersBody allows only start/stop of the installed binary, no password.
// install/uninstall/setup/repair are not listed — those stay one-time admin.
func SudoersBody(exe string) string {
	p := sudoersEscape(exe)
	return fmt.Sprintf(`# Generated by offveil-core. Do not edit.
# Demand-start: Windows SERVICE_START analogue (no password after first admin).
Defaults!OFFVEIL_CTL !requiretty
Cmnd_Alias OFFVEIL_CTL = %s start, %s stop
%%admin ALL=(root) NOPASSWD: OFFVEIL_CTL
`, p, p)
}

func sudoersEscape(path string) string {
	replacer := strings.NewReplacer(
		`\`, `\\`,
		` `, `\ `,
		`,`, `\,`,
		`:`, `\:`,
		`=`, `\=`,
	)
	return replacer.Replace(path)
}

// ElevateScript is the osascript one-liner for first-run admin (not a .pkg,
// not a Network Extension).
func ElevateScript(exe, user, action string) string {
	shell := fmt.Sprintf("OFFVEIL_SETUP_USER=%s %s %s",
		shQuote(user), shQuote(exe), shQuote(action))
	return "do shell script " + asQuote(shell) + " with administrator privileges"
}

func shQuote(s string) string {
	return "'" + strings.ReplaceAll(s, `'`, `'"'"'`) + "'"
}

func asQuote(s string) string {
	return `"` + strings.ReplaceAll(strings.ReplaceAll(s, `\`, `\\`), `"`, `\"`) + `"`
}
